FROM node:22-slim

RUN mkdir -p /home/frontend-dev

WORKDIR /home/frontend-dev

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
COPY next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["npm", "run", "dev"]
