services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
    volumes:
      - .:/home/frontend-dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env
