FROM node:22-alpine

RUN mkdir -p /home/frontend-prod

WORKDIR /home/frontend-prod

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
