services:
  frontend-dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/frontend-dev
      - /home/frontend-dev/node_modules
    environment:
      - NODE_ENV=development