name: Deploy Frontend to GCP VM

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed] # (mergeado)
    branches: [master]

jobs:
  deploy:
    if: github.event.pull_request.merged == true # Solo si se hizo merge
    name: 🚀 PRODUCTION Deploy Next.js to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 👉 Build la imagen Docker
      - name: Build Docker image
        run: docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/frontend-prod:${{ github.sha }} .

      # 👉 Log in to DockerHub
      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 👉 Push la imagen
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-prod:${{ github.sha }}

      # 👉 Add VM to known_hosts
      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Actualizar o agregar imagen en .env
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/proyectosdanils/
            sed -i '/^DOCKER_IMAGE_FRONTEND_PROD=/d' .env
            echo "DOCKER_IMAGE_FRONTEND_PROD=${{ secrets.DOCKER_USERNAME }}/frontend-prod:${{ github.sha }}" >> .env

      # 👉 Desplegar en la VM
      - name: Deploy on GCP VM
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/proyectosdanils/
            docker compose down frontend-prod
            docker compose up -d frontend-prod